# syntax=docker/dockerfile:1
FROM golang:1.26 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/groma-manager ./cmd/manager

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/groma-manager /groma-manager
USER 65532:65532
ENTRYPOINT ["/groma-manager"]
